# Generated by Django 5.0 on 2024-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
